package vista;

public class JFRecreativo extends javax.swing.JFrame {

    public JFRecreativo() {
        initComponents();
        this.setLocationRelativeTo(null);
        rsscalelabel.RSScaleLabel.setScaleLabel(fondo, "src/Imagenes/fondorecreativa.png");
        btnsamanes.setVisible(false);
        btnsantay.setVisible(false);
        btnboliche.setVisible(false);
        btnlago.setVisible(false);
        btnillizas.setVisible(false);
        btnchurute.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnatras = new javax.swing.JButton();
        Titilo = new javax.swing.JLabel();
        btnactividades = new javax.swing.JButton();
        btnreservas = new javax.swing.JButton();
        btnchurute = new javax.swing.JButton();
        btnsamanes = new javax.swing.JButton();
        btnillizas = new javax.swing.JButton();
        btnsantay = new javax.swing.JButton();
        btnboliche = new javax.swing.JButton();
        btnlago = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        btnatras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnregresar.png"))); // NOI18N
        btnatras.setBorderPainted(false);
        btnatras.setContentAreaFilled(false);
        btnatras.setFocusPainted(false);
        btnatras.setFocusable(false);
        btnatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatrasActionPerformed(evt);
            }
        });

        Titilo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Titilo.setForeground(new java.awt.Color(255, 255, 255));
        Titilo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titilo.setText("RECREATIVAS");
        Titilo.setToolTipText("");
        Titilo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Titilo.setFocusable(false);
        Titilo.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 193, Short.MAX_VALUE)
                .addComponent(Titilo, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190)
                .addComponent(btnatras))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnatras)
                    .addComponent(Titilo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 30));

        btnactividades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnrecreacionNULL.png"))); // NOI18N
        btnactividades.setBorderPainted(false);
        btnactividades.setContentAreaFilled(false);
        btnactividades.setFocusPainted(false);
        btnactividades.setFocusable(false);
        btnactividades.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnrecreacion.png"))); // NOI18N
        btnactividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactividadesActionPerformed(evt);
            }
        });
        getContentPane().add(btnactividades, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 150, 110));

        btnreservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnreservaNULL.png"))); // NOI18N
        btnreservas.setBorderPainted(false);
        btnreservas.setContentAreaFilled(false);
        btnreservas.setFocusPainted(false);
        btnreservas.setFocusable(false);
        btnreservas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnreserva.png"))); // NOI18N
        btnreservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreservasActionPerformed(evt);
            }
        });
        getContentPane().add(btnreservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 150, 110));

        btnchurute.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnchuruteNULL.png"))); // NOI18N
        btnchurute.setBorderPainted(false);
        btnchurute.setContentAreaFilled(false);
        btnchurute.setFocusPainted(false);
        btnchurute.setFocusable(false);
        btnchurute.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnchurute.png"))); // NOI18N
        btnchurute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchuruteActionPerformed(evt);
            }
        });
        getContentPane().add(btnchurute, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 150, 70));

        btnsamanes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnsamanesNULL.png"))); // NOI18N
        btnsamanes.setBorderPainted(false);
        btnsamanes.setContentAreaFilled(false);
        btnsamanes.setFocusPainted(false);
        btnsamanes.setFocusable(false);
        btnsamanes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnsamanes.png"))); // NOI18N
        btnsamanes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsamanesActionPerformed(evt);
            }
        });
        getContentPane().add(btnsamanes, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 150, 70));

        btnillizas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnIllinisasNULL.png"))); // NOI18N
        btnillizas.setBorderPainted(false);
        btnillizas.setContentAreaFilled(false);
        btnillizas.setFocusPainted(false);
        btnillizas.setFocusable(false);
        btnillizas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnIllinisas.png"))); // NOI18N
        btnillizas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnillizasActionPerformed(evt);
            }
        });
        getContentPane().add(btnillizas, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 150, 70));

        btnsantay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnsantayNULL.png"))); // NOI18N
        btnsantay.setBorderPainted(false);
        btnsantay.setContentAreaFilled(false);
        btnsantay.setFocusPainted(false);
        btnsantay.setFocusable(false);
        btnsantay.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnsantay.png"))); // NOI18N
        btnsantay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsantayActionPerformed(evt);
            }
        });
        getContentPane().add(btnsantay, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 150, 70));

        btnboliche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnbolicheNULL.png"))); // NOI18N
        btnboliche.setBorderPainted(false);
        btnboliche.setContentAreaFilled(false);
        btnboliche.setFocusPainted(false);
        btnboliche.setFocusable(false);
        btnboliche.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnboliche.png"))); // NOI18N
        btnboliche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbolicheActionPerformed(evt);
            }
        });
        getContentPane().add(btnboliche, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 150, 70));

        btnlago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnlagoNULL.png"))); // NOI18N
        btnlago.setBorderPainted(false);
        btnlago.setContentAreaFilled(false);
        btnlago.setFocusPainted(false);
        btnlago.setFocusable(false);
        btnlago.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnlago.png"))); // NOI18N
        btnlago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlagoActionPerformed(evt);
            }
        });
        getContentPane().add(btnlago, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 150, 70));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 720, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatrasActionPerformed
            JFActividades a=new JFActividades();
            a.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_btnatrasActionPerformed

    private void btnreservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreservasActionPerformed
        if (!this.btnreservas.isSelected()) {
            btnsamanes.setVisible(false);
            btnsantay.setVisible(false);
            btnboliche.setVisible(false);
            btnlago.setVisible(false);
            btnillizas.setVisible(true);
            btnchurute.setVisible(true);
        }
    }//GEN-LAST:event_btnreservasActionPerformed

    private void btnactividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactividadesActionPerformed
        if (!this.btnactividades.isSelected()) {
            btnsamanes.setVisible(true);
            btnsantay.setVisible(true);
            btnboliche.setVisible(true);
            btnlago.setVisible(true);
            btnillizas.setVisible(false);
            btnchurute.setVisible(false);
        }
    }//GEN-LAST:event_btnactividadesActionPerformed

    private void btnsantayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsantayActionPerformed
        JFSantay s=new JFSantay();
        s.setVisible(true);
        this.dispose();
                
    }//GEN-LAST:event_btnsantayActionPerformed

    private void btnlagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlagoActionPerformed
        JFLago l= new JFLago();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnlagoActionPerformed

    private void btnillizasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnillizasActionPerformed
        JFIllinizas i= new JFIllinizas();
        i.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnillizasActionPerformed

    private void btnchuruteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchuruteActionPerformed
        JFChurute c= new JFChurute();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnchuruteActionPerformed

    private void btnsamanesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsamanesActionPerformed
        JFSamanes s= new JFSamanes();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnsamanesActionPerformed

    private void btnbolicheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbolicheActionPerformed
        JFBoliche b= new JFBoliche();
        b.setVisible(true);
        this.dispose();                
    }//GEN-LAST:event_btnbolicheActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFRecreativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFRecreativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFRecreativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFRecreativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFRecreativo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titilo;
    private javax.swing.JButton btnactividades;
    private javax.swing.JButton btnatras;
    private javax.swing.JButton btnboliche;
    private javax.swing.JButton btnchurute;
    private javax.swing.JButton btnillizas;
    private javax.swing.JButton btnlago;
    private javax.swing.JButton btnreservas;
    private javax.swing.JButton btnsamanes;
    private javax.swing.JButton btnsantay;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
